/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Sistema;

import com.mycompany.Classes.Evento;
import com.mycompany.Classes.Ciclone;
import com.mycompany.Classes.Seca;
import com.mycompany.Classes.Terremoto;
/**
 *
 * @author Julio
 */
public class Tela extends javax.swing.JFrame {
    
    private ACMERescue acme;
    /**
     * Creates new form Tela
     */
    public Tela() {
        super();
        initComponents();
        acme = new ACMERescue();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTela = new javax.swing.JPanel();
        jtTela = new javax.swing.JTabbedPane();
        jtACMER = new javax.swing.JTabbedPane();
        jtCadastra = new javax.swing.JTabbedPane();
        jtCadastraEvento = new javax.swing.JTabbedPane();
        jpCadastraCiclone = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfCiclone1 = new javax.swing.JTextField();
        jtfCiclone2 = new javax.swing.JTextField();
        jtfCiclone3 = new javax.swing.JTextField();
        jtfCiclone4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtfCiclone5 = new javax.swing.JTextField();
        jtfCiclone6 = new javax.swing.JTextField();
        jbCadastraCiclone = new javax.swing.JButton();
        jpCadastraTerremoto = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfTerremoto1 = new javax.swing.JTextField();
        jtfTerremoto2 = new javax.swing.JTextField();
        jtfTerremoto3 = new javax.swing.JTextField();
        jtfTerremoto4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfTerremoto5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jpCadastraSeca = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfSeca1 = new javax.swing.JTextField();
        jtfSeca2 = new javax.swing.JTextField();
        jtfSeca3 = new javax.swing.JTextField();
        jtfSeca4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfSeca5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jtCadastraEquipe = new javax.swing.JTabbedPane();
        jtCadastraEquipamento = new javax.swing.JTabbedPane();
        jtCadastraAtendimento = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpTela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtTela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtACMER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtACMER.setToolTipText("");
        jtTela.addTab("ACMER", jtACMER);

        jtCadastra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtCadastraEvento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("codigo");

        jLabel2.setText("data");

        jLabel3.setText("latitude");

        jLabel4.setText("longitude");

        jtfCiclone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCiclone1ActionPerformed(evt);
            }
        });

        jLabel13.setText("velocidade");

        jLabel14.setText("precipitacao");

        jbCadastraCiclone.setText("OK");
        jbCadastraCiclone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastraCicloneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadastraCicloneLayout = new javax.swing.GroupLayout(jpCadastraCiclone);
        jpCadastraCiclone.setLayout(jpCadastraCicloneLayout);
        jpCadastraCicloneLayout.setHorizontalGroup(
            jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastraCicloneLayout.createSequentialGroup()
                .addGroup(jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastraCicloneLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfCiclone1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jtfCiclone2))
                        .addGap(45, 45, 45)
                        .addGroup(jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpCadastraCicloneLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfCiclone5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastraCicloneLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfCiclone6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpCadastraCicloneLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCadastraCicloneLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCiclone4))
                            .addGroup(jpCadastraCicloneLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCiclone3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88)
                        .addComponent(jbCadastraCiclone)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jpCadastraCicloneLayout.setVerticalGroup(
            jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastraCicloneLayout.createSequentialGroup()
                .addGroup(jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastraCicloneLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jtfCiclone5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastraCicloneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfCiclone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfCiclone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCiclone6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastraCicloneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCiclone3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCadastraCicloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfCiclone4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpCadastraCicloneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jbCadastraCiclone)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jtCadastraEvento.addTab("Ciclone", jpCadastraCiclone);

        jpCadastraTerremoto.setRequestFocusEnabled(false);

        jLabel9.setText("codigo");

        jLabel10.setText("data");

        jLabel11.setText("latitude");

        jLabel12.setText("longitude");

        jtfTerremoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTerremoto1ActionPerformed(evt);
            }
        });

        jLabel15.setText("magnitude");

        jtfTerremoto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTerremoto5ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadastraTerremotoLayout = new javax.swing.GroupLayout(jpCadastraTerremoto);
        jpCadastraTerremoto.setLayout(jpCadastraTerremotoLayout);
        jpCadastraTerremotoLayout.setHorizontalGroup(
            jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastraTerremotoLayout.createSequentialGroup()
                .addGroup(jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastraTerremotoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTerremoto1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jtfTerremoto2))
                        .addGap(67, 67, 67)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTerremoto5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCadastraTerremotoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCadastraTerremotoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfTerremoto4))
                            .addGroup(jpCadastraTerremotoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jtfTerremoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpCadastraTerremotoLayout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(jButton2)
                    .addContainerGap(260, Short.MAX_VALUE)))
        );
        jpCadastraTerremotoLayout.setVerticalGroup(
            jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastraTerremotoLayout.createSequentialGroup()
                .addGroup(jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastraTerremotoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfTerremoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jtfTerremoto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastraTerremotoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfTerremoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTerremoto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfTerremoto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jpCadastraTerremotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpCadastraTerremotoLayout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(jButton2)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        jtCadastraEvento.addTab("Terremoto", jpCadastraTerremoto);

        jLabel5.setText("codigo");

        jLabel6.setText("data");

        jLabel7.setText("latitude");

        jLabel8.setText("longitude");

        jtfSeca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSeca1ActionPerformed(evt);
            }
        });

        jLabel16.setText("estiagem");

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadastraSecaLayout = new javax.swing.GroupLayout(jpCadastraSeca);
        jpCadastraSeca.setLayout(jpCadastraSecaLayout);
        jpCadastraSecaLayout.setHorizontalGroup(
            jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastraSecaLayout.createSequentialGroup()
                .addGroup(jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastraSecaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfSeca1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jtfSeca2))
                        .addGap(73, 73, 73)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSeca5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCadastraSecaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCadastraSecaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfSeca4))
                            .addGroup(jpCadastraSecaLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jtfSeca3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpCadastraSecaLayout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(jButton3)
                    .addContainerGap(260, Short.MAX_VALUE)))
        );
        jpCadastraSecaLayout.setVerticalGroup(
            jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastraSecaLayout.createSequentialGroup()
                .addGroup(jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastraSecaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfSeca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jtfSeca5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastraSecaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfSeca2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSeca3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfSeca4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jpCadastraSecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpCadastraSecaLayout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(jButton3)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        jtCadastraEvento.addTab("Seca", jpCadastraSeca);

        jtCadastra.addTab("Evento", jtCadastraEvento);

        jtCadastraEquipe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtCadastra.addTab("Equipe", jtCadastraEquipe);

        jtCadastraEquipamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtCadastra.addTab("Equipamento", jtCadastraEquipamento);

        jtCadastraAtendimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtCadastra.addTab("Atendimento", jtCadastraAtendimento);

        jtTela.addTab("Cadastra", jtCadastra);

        jButton1.setText("Relatorio Geral");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        jtTela.addTab("Mostrar", jPanel1);

        Area.setColumns(20);
        Area.setRows(5);
        jScrollPane1.setViewportView(Area);

        javax.swing.GroupLayout jpTelaLayout = new javax.swing.GroupLayout(jpTela);
        jpTela.setLayout(jpTelaLayout);
        jpTelaLayout.setHorizontalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtTela)
            .addGroup(jpTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jpTelaLayout.setVerticalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaLayout.createSequentialGroup()
                .addComponent(jtTela, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCiclone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCiclone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCiclone1ActionPerformed

    private void jtfSeca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSeca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSeca1ActionPerformed

    private void jtfTerremoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTerremoto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTerremoto1ActionPerformed

    private void jtfTerremoto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTerremoto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTerremoto5ActionPerformed

    private void jbCadastraCicloneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastraCicloneActionPerformed
        if(acme.verificaCodigo(jtfCiclone1.getText())){
            acme.cadastraCiclone(new Ciclone(jtfCiclone1.getText(), jtfCiclone2.getText(), Double.parseDouble(jtfCiclone3.getText()), Double.parseDouble(jtfCiclone4.getText()), Double.parseDouble(jtfCiclone5.getText()), Double.parseDouble(jtfCiclone6.getText())));
            Area.append("\ncadastrado com sucesso\n");
        }
        else{
            Area.append("\nerro: codigo ja existe\n");
        }
        
        
        
        
    }//GEN-LAST:event_jbCadastraCicloneActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (acme.verificaCodigo(jtfTerremoto1.getText())) {
            acme.cadastraTerremoto(new Terremoto(jtfTerremoto1.getText(), jtfTerremoto2.getText(), Double.parseDouble(jtfTerremoto3.getText()), Double.parseDouble(jtfTerremoto4.getText()), Double.parseDouble(jtfTerremoto5.getText())));
            Area.append("\ncadastrado com sucesso\n");
        } else {
            Area.append("\nerro: codigo ja existe\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(acme.verificaCodigo(jtfSeca1.getText())){
            acme.cadastraSeca(new Seca(jtfSeca1.getText(),jtfSeca2.getText(),Double.parseDouble(jtfSeca3.getText()),Double.parseDouble(jtfSeca4.getText()),Integer.parseInt(jtfSeca5.getText())));
            Area.append("\ncadastrado com sucesso\n");
        }else {
            Area.append("\nerro: codigo ja existe\n");
        }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(acme.mostrarRelatorio().equals("")){
            Area.append("nenhuma equipe cadastrada");
        }
        else{
            Area.append(acme.mostrarRelatorio());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCadastraCiclone;
    private javax.swing.JPanel jpCadastraCiclone;
    private javax.swing.JPanel jpCadastraSeca;
    private javax.swing.JPanel jpCadastraTerremoto;
    private javax.swing.JPanel jpTela;
    private javax.swing.JTabbedPane jtACMER;
    private javax.swing.JTabbedPane jtCadastra;
    private javax.swing.JTabbedPane jtCadastraAtendimento;
    private javax.swing.JTabbedPane jtCadastraEquipamento;
    private javax.swing.JTabbedPane jtCadastraEquipe;
    private javax.swing.JTabbedPane jtCadastraEvento;
    private javax.swing.JTabbedPane jtTela;
    private javax.swing.JTextField jtfCiclone1;
    private javax.swing.JTextField jtfCiclone2;
    private javax.swing.JTextField jtfCiclone3;
    private javax.swing.JTextField jtfCiclone4;
    private javax.swing.JTextField jtfCiclone5;
    private javax.swing.JTextField jtfCiclone6;
    private javax.swing.JTextField jtfSeca1;
    private javax.swing.JTextField jtfSeca2;
    private javax.swing.JTextField jtfSeca3;
    private javax.swing.JTextField jtfSeca4;
    private javax.swing.JTextField jtfSeca5;
    private javax.swing.JTextField jtfTerremoto1;
    private javax.swing.JTextField jtfTerremoto2;
    private javax.swing.JTextField jtfTerremoto3;
    private javax.swing.JTextField jtfTerremoto4;
    private javax.swing.JTextField jtfTerremoto5;
    // End of variables declaration//GEN-END:variables
}
